config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :bikes do
    resources :maintenances
    resources :schedules, only: [:show, :new, :create, :update, :edit]
  end

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :bike

  validates :oil, presence: true
  validates :sparkplugs, presence: true
  validates :airfilter, presence: true
  validates :oilfilter, presence: true
  validates :coolingfluid, presence: true
  validates :chain, presence: true
  validates :break_front, presence: true
  validates :break_back, presence: true
  validates :breakfluid, presence: true
  validates :tyres, presence: true
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update]
  before_action :set_bike_name, only: [:show, :new]
  before_action :set_bike, only: [:new, :create, :show, :edit]

  def show

  end

  def new
    @schedule = Schedule.new

  end

  def create
    @new_schedule = @bike.build_schedule(schedule_params)
    if @new_schedule.save
      flash[:notice] = "Schedule successfully created"
      redirect_to bike_schedule_path(@bike, @bike.schedule)
    else
      flash[:alert] = "Schedule could not be created"
      redirect_to new_bike_schedule_path
    end
  end

  def edit

  end

  def update
    if @schedule.update(schedule_params)
      flash[:notice] = "Maintenance schedule successfully updated"
      redirect_to bike_schedule_path
    else
      flash[:alert] = "Maintenance schedule update failed"
      redirect_to bike_schedule_path
    end
  end

  private

    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    def set_bike
      @bike = Bike.find(params[:bike_id])
    end

    def set_bike_name
      @bike_name = Bike.find(params[:bike_id]).name
    end

    def schedule_params
      params.require(:schedule).permit(:oil, :sparkplugs, :airfilter, :oilfilter, :coolingfluid, :chain, :break_front, :break_back, :breakfluid, :tyres)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_schedules_form.html.erb
    <div class="panel-body">
      <%= form_for [@bike, @schedule] do |schedule| %>
        <% if @schedule.errors.any? %>
          <% @schedule.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
        <div class="form-group">
          Oil change: <%= schedule.number_field :oil , placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>
        <div class="form-group">
          Sparkplugs replaced: <%= schedule.number_field :sparkplugs, placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>
        <div class="form-group">
          Airfilter replaced: <%= schedule.number_field :airfilter, placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>
        <div class="form-group">
          Oilfilter replaced: <%= schedule.number_field :oilfilter, placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>
        <div class="form-group">
          Coolingfluid changed: <%= schedule.number_field :coolingfluid, placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>
        <div class="form-group">
          Chain replaced: <%= schedule.number_field :chain, placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>
        <div class="form-group">
          Front brake replaced: <%= schedule.number_field :break_front, placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>
        <div class="form-group">
          Rear brake replaced: <%= schedule.number_field :break_back, placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>
        <div class="form-group">
          brakefluid changed: <%= schedule.number_field :breakfluid, placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>
        <div class="form-group">
          New tyres: <%= schedule.number_field :tyres, placeholder: "Enter amount of kilometers", class: "form-control" %>
        </div>

        <%= schedule.submit (@schedule.new_record? ? "Create" : "Update"), class: "btn btn-default" %>
        <%= link_to "Back to your bikes", bikes_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/schedules/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Edit the maintenance schedule for <%= @bike_name %></div>
    <%= render 'schedules_form' %>

app/views/schedules/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Create a maintenance schedule for <%= @bike_name %></div>
    <%= render 'schedules_form' %>

app/views/schedules/show.html.erb
<div>
  <div class="panel panel-primary">
    <div class="panel-heading">Maintenance schedule for <%= @bike_name %></div>
    <div class="panel-body">
      <table class="table table-striped">
        <tbody>
          <tr>
            <th></th>
            <th>Kilometers</th>
          </tr>
          <tr>
            <th>Oil:</th>
            <td><%= @schedule.oil %></td>
          </tr>
          <tr>
            <th>Sparkplugs:</th>
            <td><%= @schedule.sparkplugs %></td>
          </tr>
          <tr>
            <th>Airfilter:</th>
            <td><%= @schedule.airfilter %></td>
          </tr>
          <tr>
            <th>Oilfilter:</th>
            <td><%= @schedule.oilfilter %></td>
          </tr>
          <tr>
            <th>Coolingfluid:</th>
            <td><%= @schedule.coolingfluid %></td>
          </tr>
          <tr>
            <th>Chain:</th>
            <td><%= @schedule.chain %></td>
          </tr>
          <tr>
            <th>Front breaks:</th>
            <td><%= @schedule.break_front %></td>
          </tr>
          <tr>
            <th>Back breaks:</th>
            <td><%= @schedule.break_back %></td>
          </tr>
          <tr>
            <th>Breakfluid:</th>
            <td><%= @schedule.breakfluid %></td>
          </tr>
          <tr>
            <th>Tires:</th>
            <td><%= @schedule.tyres %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= link_to "EDIT", edit_bike_schedule_path(@bike, @schedule), class: "btn btn-default" %>
<%= link_to "Back to bikes", bikes_path, class: "btn btn-default" %>