config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :bikes do
    resources :maintenances
    resources :schedules, only: [:show, :new, :create, :update, :edit]
  end

end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :maintenances, dependent: :destroy
  has_one :schedule, dependent: :destroy

  validates :name, presence: true, length: { maximum: 15 }
  validates :brand, presence: true, length: { maximum: 10 }
  validates :model, presence: true, length: { maximum: 15 }
  validates :build, presence: true,
            format: { with: /(19|20)\d{2}/i },
            numericality: {
              greater_than_or_equal_to: 1900,
              less_than_or_equal_to: Date.today.year
            }
  validates :odometer, presence: true, length: { maximum: 6 }

  def has_schedule?
    schedule.present? && schedule.persisted?
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update]
  before_action :authenticate_user!

  def index
    @bikes = current_user.bikes
  end

  def show
  end

  def new
    @bike = current_user.bikes.build
  end

  def create
    @bike = current_user.bikes.build(bike_params)

    if @bike.save
      redirect_to @bike, notice: "You registrated a new bike, congrats!"
    else
      render :new
    end
  end

  def update
    if @bike.update(bike_params)
      redirect_to @bike, notice: "Your motorbike has been updated"
    else
      render :edit
    end
  end


  private

    def set_bike
      @bike = Bike.find(params[:id])
    end

    def bike_params
      params.require(:bike).permit(:name, :brand, :model, :build, :odometer)
    end

end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/_form.html.erb
<%= form_for @bike do |bike| %>
  <div class="form-group">
    <label for="name">Name:</label>
    <%= bike.text_field :name, placeholder: "Enter your bike's name", class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="brand">Brand:</label>
    <%= bike.text_field :brand, placeholder: "Enter the brand of your bike", class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="model">Model:</label>
    <%= bike.text_field :model, placeholder: "Enter the model type", class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="brand">Year:</label>
    <%= bike.number_field :build, placeholder: "Enter year of production", class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="brand">Odometer:</label>
    <%= bike.number_field :odometer, placeholder: "Enter the amount of km on your odometer", class: "form-control" %>
  </div>
  <%= bike.submit "Create Bike", class: "btn btn-default" %>
<% end %>

app/views/bikes/index.html.erb
<div>
  <div class="panel panel-primary">
    <div class="panel-heading">Your Bikes</div>
    <div class="panel-body">
      <div class="col-xs-12 bikes-container">
        <% @bikes.each do |bike| %>
          <div class="bike-wrapper">
              <h4><%= bike.name %></h4>
              <div>Brand: <%= bike.brand %></div>
              <div>Model: <%= bike.model %></div>
              <div>Year: <%= bike.build %></div>
              <div>Meter: <%= bike.odometer %></div>
               <%= link_to "View", bike, class: "btn btn-default" %>
               <%= link_to "Maintenance", bike_maintenances_path(bike), class: "btn btn-default" %>
               <% if bike.has_schedule? %>
                 <%= link_to "Show Schedule", bike_schedule_path(bike, bike.schedule), class: "btn btn-default" %>
               <% else %>
                 <%= link_to "Create Schedule", new_bike_schedule_path(bike), class: "btn btn-default" %>
               <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= link_to "Add new bike", new_bike_path, class: "btn btn-primary" %>
</div>

app/views/bikes/new.html.erb
<h2>create a new bike</h2>

<%= render 'form' %>

<%= link_to "Back", bikes_path, class: "btn btn-default" %>

app/views/bikes/show.html.erb
<h4><%= @bike.name %></h4>

<div>Brand: <%= @bike.brand %></div>
<div>Model: <%= @bike.model %></div>
<div>Year: <%= @bike.build %></div>
<div>Meter: <%= @bike.odometer %></div>

<%= link_to "Back to bikes", bikes_path, class: "btn btn-default" %>