config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :bikes do
    resources :maintenances
    resources :schedules, only: [:show, :new, :create, :update, :edit]
  end

end

app/models/maintenance.rb
class Maintenance < ApplicationRecord
  belongs_to :bike

  validates :odometer, presence: true, length: { maximum: 6 }
  validates :date, presence: true , format: { with: /(19|20)\d{2}/i }
  validates :oil, inclusion: [true, false]
  validates :sparkplugs, inclusion: [true, false]
  validates :airfilter, inclusion: [true, false]
  validates :oilfilter, inclusion: [true, false]
  validates :coolingfluid, inclusion: [true, false]
  validates :chain, inclusion: [true, false]
  validates :break_front, inclusion: [true, false]
  validates :break_back, inclusion: [true, false]
  validates :breakfluid, inclusion: [true, false]
  validates :tyres, inclusion: [true, false]

  def self.find_bike_maintenances(bike_id)
    bike_maintenances = Maintenance.select{ |maintenance| maintenance.bike_id == bike_id }
    return bike_maintenances
  end

  def self.sort_by_date_from_old_to_current(bike_maintenances)
    bike_maintenances.sort! { |a,b| a.date <=> b.date }
    return bike_maintenances
  end

  def self.calculate_km(bike_maintenances, current_odometer)
    sort_by_date_from_current_to_old(bike_maintenances)
    kilometers = set_km_to_no_maintenance(current_odometer) #kilometers = {} # create new object that will receive all km
    find_last_item_maintenance(bike_maintenances, kilometers, current_odometer)
    return kilometers
  end

  def self.sort_by_date_from_current_to_old(bike_maintenances)
    bike_maintenances.sort! { |a,b| b.date <=> a.date }
  end

  def self.find_last_item_maintenance(bike_maintenances, kilometers, current_odometer)
    bike_maintenances.each do |maintenance|
      if ((kilometers[:oil] === current_odometer) && (maintenance.oil === true))
        kilometers[:oil] = (current_odometer - maintenance.odometer)
      end
      if ((kilometers[:sparkplugs] === current_odometer) && (maintenance.sparkplugs === true))
        kilometers[:sparkplugs] = (current_odometer - maintenance.odometer)
      end
      if ((kilometers[:airfilter] === current_odometer) && (maintenance.airfilter === true))
        kilometers[:airfilter] = (current_odometer - maintenance.odometer)
      end
      if ((kilometers[:oilfilter] === current_odometer) && (maintenance.oilfilter === true))
        kilometers[:oilfilter] = (current_odometer - maintenance.odometer)
      end
      if ((kilometers[:coolingfluid] === current_odometer) && (maintenance.coolingfluid === true))
        kilometers[:coolingfluid] = (current_odometer - maintenance.odometer)
      end
      if ((kilometers[:chain] === current_odometer) && (maintenance.chain === true))
        kilometers[:chain] = (current_odometer - maintenance.odometer)
      end
    if ((kilometers[:break_front] === current_odometer) && (maintenance.break_front === true))
        kilometers[:break_front] = (current_odometer - maintenance.odometer)
      end
      if ((kilometers[:break_back] === current_odometer) && (maintenance.break_back === true))
        kilometers[:break_back] = (current_odometer - maintenance.odometer)
      end
      if ((kilometers[:breakfluid] === current_odometer) && (maintenance.breakfluid === true))
        kilometers[:breakfluid] = (current_odometer - maintenance.odometer)
      end
      if ((kilometers[:tyres] === current_odometer) && (maintenance.tyres === true))
        kilometers[:tyres] = (current_odometer - maintenance.odometer)
      end
    end
  end

  def self.set_km_to_no_maintenance(current_odometer)
    return kilometers = {
      oil: current_odometer,
      sparkplugs: current_odometer,
      airfilter: current_odometer,
      oilfilter: current_odometer,
      coolingfluid: current_odometer,
      chain: current_odometer,
      break_front: current_odometer,
      break_back: current_odometer,
      breakfluid: current_odometer,
      tyres: current_odometer,
    }
  end

end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController
  before_action :set_maintenance, only: [:edit, :update, :destroy]
  before_action :set_bike, only: [:index, :new, :create, :edit]
  before_action :authenticate_user!

  def index
    @bike_maintenances = Maintenance.find_bike_maintenances(params[:bike_id].to_i)
    @km_ago = Maintenance.calculate_km(@bike_maintenances, @bike.odometer)
    @bike_maintenances = Maintenance.sort_by_date_from_old_to_current(@bike_maintenances)
  end

  def new
    @maintenance = Maintenance.new
  end

  def create
    @new_maintenance = @bike.maintenances.build(maintenance_params)
    if @new_maintenance.save
      flash[:notice] = "Maintenance successfully added"
      redirect_to bike_maintenances_path
    else
      flash[:alert] = "Maintenance build failed"
      redirect_to new_bike_maintenance_path
    end
  end

  def edit

  end

  def update
    if @maintenance.update(maintenance_params)
      flash[:notice] = "Maintenance successfully updated"
      redirect_to bike_maintenances_path
    else
      flash[:alert] = "Maintenance update failed"
      redirect_to edit_bike_maintenance_path
    end
  end

  def destroy
    if @maintenance.destroy
      flash[:notice] = "Maintenance successfully deleted"
      redirect_to bike_maintenances_path
    else
      flash[:alert] = "Unsuccessful in deleting maintenance"
      redirect_to bike_maintenances_path
    end
  end

  private

    def set_maintenance
      @maintenance = Maintenance.find(params[:id])
    end

    def set_bike
      @bike = Bike.find(params[:bike_id])
    end

    def maintenance_params
      params.require(:maintenance).permit(:date, :odometer, :costs, :oil, :sparkplugs, :airfilter, :oilfilter, :coolingfluid, :chain, :break_front, :break_back, :breakfluid, :tyres)
    end
end

app/helpers/maintenances_helper.rb
module MaintenancesHelper
end

app/views/maintenances/_maintenance_form.html.erb
    <div class="panel-body">
      <%= form_for [@bike, @maintenance] do |maintenance| %>
        <div class="form-group">
          <label>Maintenance date:</label>
          <%= maintenance.date_field :date, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Odometer:</label>
            <%= maintenance.number_field :odometer, placeholder: "Enter the odometer stand", class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Costs:</label>
            <%= maintenance.number_field :costs, placeholder: "Enter the costs of the maintenance", class: "text-field form-control", step: 0.01 %>
        </div>

        <label>Maintenances</label>

        <div class="form-group">
          Oil change: <%= maintenance.select :oil , [["no", false], ["yes", true]], class: "form-control" %>
        </div>
        <div class="form-group">
          Sparkplugs replaced: <%= maintenance.select :sparkplugs, [["no", false], ["yes", true]], class: "form-control" %>
        </div>
        <div class="form-group">
          Airfilter replaced: <%= maintenance.select :airfilter, [["no", false], ["yes", true]], class: "form-control" %>
        </div>
        <div class="form-group">
          Oilfilter replaced: <%= maintenance.select :oilfilter, [["no", false], ["yes", true]], class: "form-control" %>
        </div>
        <div class="form-group">
          Coolingfluid changed: <%= maintenance.select :coolingfluid, [["no", false], ["yes", true]], class: "form-control" %>
        </div>
        <div class="form-group">
          Chain replaced: <%= maintenance.select :chain, [["no", false], ["yes", true]], class: "form-control" %>
        </div>
        <div class="form-group">
          Front brake replaced: <%= maintenance.select :break_front, [["no", false], ["yes", true]], class: "form-control" %>
        </div>
        <div class="form-group">
          Rear brake replaced: <%= maintenance.select :break_back, [["no", false], ["yes", true]], class: "form-control" %>
        </div>
        <div class="form-group">
          brakefluid changed: <%= maintenance.select :breakfluid, [["no", false], ["yes", true]], class: "form-control" %>
        </div>
        <div class="form-group">
          New tyres: <%= maintenance.select :tyres, [["no", false], ["yes", true]], class: "form-control" %>
        </div>

        <%= maintenance.submit (@maintenance.new_record? ? "Create" : "Update"), class: "btn btn-default" %>
        <%= link_to "Back to your bikes maintenances", bike_maintenances_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/maintenances/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Edit maintenance of bike <%= @bike.name %></div>
    <%= render 'maintenance_form' %>

app/views/maintenances/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Maintenance of bike <%= @bike.name %></div>
  <div class="panel-body">
    <div class="col-xs-12 maintenance-container">
      <%= link_to "Add New Maintenance", new_bike_maintenance_path, class: "btn btn-default" %>
      <table class="table table-striped">
        <tbody>
          <tr>
            <th>
              Maintenance date:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.date %></td>
            <% end %>
            <td>
              kilometers since last maintenance:
            </td>
          </tr>
          <tr>
            <th>
              Odometer:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.odometer %></td>
            <% end %>
          </tr>
          <tr>
            <th>
              Costs:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.costs %></td>
            <% end %>
          </tr>
          <tr>
            <th>
              Oil change:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.oil %></td>
            <% end %>
            <td>
              <%= @km_ago[:oil] %>
            </td>
          </tr>
          <tr>
            <th>
              Sparkplugs replaced:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.sparkplugs %></td>
            <% end %>
            <td>
              <%= @km_ago[:sparkplugs] %>
            </td>
          </tr>
          <tr>
            <th>
              Airfilter replaced:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.airfilter %></td>
            <% end %>
            <td>
              <%= @km_ago[:airfilter] %>
            </td>
          </tr>
          <tr>
            <th>
              Oilfilter replaced:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.oilfilter %></td>
            <% end %>
            <td>
              <%= @km_ago[:oilfilter] %>
            </td>
          </tr>
          <tr>
            <th>
              Coolingfluid replaced:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.coolingfluid %></td>
            <% end %>
            <td>
              <%= @km_ago[:coolingfluid] %>
            </td>
          </tr>
          <tr>
            <th>
              Chain replaced:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.chain %></td>
            <% end %>
            <td>
              <%= @km_ago[:chain] %>
            </td>
          </tr>
          <tr>
            <th>
              Front break replaced:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.break_front %></td>
            <% end %>
            <td>
              <%= @km_ago[:break_front] %>
            </td>
          </tr>
          <tr>
            <th>
              Rear brake replaced:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.break_back %></td>
            <% end %>
            <td>
              <%= @km_ago[:break_back] %>
            </td>
          </tr>
          <tr>
            <th>
              Brake fluid replaced:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.breakfluid %></td>
            <% end %>
            <td>
              <%= @km_ago[:breakfluid] %>
            </td>
          </tr>
          <tr>
            <th>
              New tyres:
            </th>
            <% @bike_maintenances.each do |maintenance| %>
              <td><%= maintenance.tyres %></td>
            <% end %>
            <td>
              <%= @km_ago[:tyres] %>
            </td>
          </tr>
          <tr>
            <th></th>
            <% @bike_maintenances.each do |maintenance| %>
              <td>
                <%= link_to "EDIT", edit_bike_maintenance_path(@bike, maintenance), class: "btn btn-default" %>
                <%= link_to "DELETE", bike_maintenance_path(@bike, maintenance), method: :delete, data: { confirm: "Are you sure you want to delelte this maintenance?" }, class: "btn btn-default" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= link_to "Back to bikes", bikes_path, class: "btn btn-default" %>

app/views/maintenances/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Add new maintenance of bike <%= @bike.name %></div>
    <%= render 'maintenance_form' %>